SELECT * FROM TBL_COUNTRY;
SELECT * FROM TBL_BRANCH;
SELECT * FROM TBL_BUILDING;
SELECT * FROM TBL_ROOF;
SELECT * FROM TBL_SITE;
SELECT * FROM TBL_CLIENT;
DESCRIBE TBL_COUNTRY;
SELECT BRANCHADDRESS, BRANCHEMAIL FROM tbl_branch;
SELECT BRANCHADDRESS AS ADDRESS, BRANCHEMAIL AS EMAIL FROM TBL_BRANCH;
SELECT BRANCHPHONE AS " PHONE NUMBER ", BRANCHADDRESS AS ADDRESS FROM TBL_BRANCH;

SELECT BRANCHNAME AS "NAME", BRANCHEMAIL AS "EMAIL", BRANCHPHONE AS " PHONE NUMBER " FROM TBL_BRANCH;
SELECT COUNTRYNAME AS "NAME OF COUNTRY", COUNTRYCAPITAL AS "CAPITAL" FROM TBL_COUNTRY;

SELECT CLIENTNAME, COMPANYNAME FROM TBL_CLIENT;

SELECT BUILDINGTYPE FROM TBL_BUILDING;
SELECT distinct BUILDINGTYPE FROM TBL_BUILDING;

SELECT 12+14 FROM DUAL;

SELECT SITEADDRESS, STARTDATE, ENDDATE FROM TBL_SITE;
SELECT ROOFTYPE, ROOFANGLE, ROOFSOILDEPTH FROM TBL_ROOF;
SELECT CLIENTNAME, CLIENTEMAIL, CLIENTPHONE FROM TBL_CLIENT;

SELECT COMPANYNAME FROM TBL_CLIENT;

SELECT sysdate();